SET SCHEMA FN71904#

-- Изглед, който показва броя на епизодите и броя на сезоните в които е участвал всеки актьор
CREATE VIEW FN71904.actorsStatisticsView(ACTORSERIALNAME, EPISODESNUMBER, SEASONSNUMBER)
AS
    SELECT A.SERIALNAME, COUNT(E.NAME), COUNT(DISTINCT S.NUMBER)
    FROM ACTORS AS A, STARSIN AS ST,
        EPISODES AS E, SEASONS AS S
    WHERE A.SERIALNAME = ST.ACTORNAME
    AND ST.EPISODENAME = E.NAME
    AND E.SEASONNUMBER = S.NUMBER
    GROUP BY A.SERIALNAME#

SELECT * FROM FN71904.actorsStatisticsView#


-- Изглед, който показва на колко години е бил всеки директор, когато е започнал да работи за сериала
CREATE VIEW FN71904.directorsStartedAgeView(UCN, DIRECTORNAME, AGE)
AS
    SELECT D.UCN, D.NAME, MIN(YEAR(S.STARTDATE - D.BIRTHDATE))
    FROM DIRECTORS AS D, DIRECTS AS DR,
        EPISODES AS E, SEASONS AS S
    WHERE D.UCN = DR.UCNDIRECTOR
    AND DR.EPISODENAME = E.NAME
    AND E.SEASONNUMBER = S.NUMBER
    GROUP BY D.UCN, D.NAME#

SELECT * FROM FN71904.directorsStartedAgeView#









-------
 SELECT E.NAME, S.NUMBER, D.NAME, A.SERIALNAME
    FROM EPISODES AS E, SEASONS AS S,
         DIRECTS AS DR, DIRECTORS AS D,
         STARSIN AS ST, ACTORS AS A
    WHERE E.SEASONNUMBER = S.NUMBER
    AND E.NAME = DR.EPISODENAME AND DR.UCNDIRECTOR = D.UCN
    AND E.NAME = ST.EPISODENAME AND ST.ACTORNAME = A.SERIALNAME#
----------


------------
SELECT D.UCN, D.NAME, COUNT(E.NAME), COUNT(DISTINCT S.NUMBER)
FROM DIRECTORS AS D, DIRECTS AS DR,
     EPISODES AS E, SEASONS AS S
WHERE D.UCN = DR.UCNDIRECTOR
AND DR.EPISODENAME = E.NAME
AND E.SEASONNUMBER = S.NUMBER
GROUP BY D.UCN, D.NAME#
------------
-- trudoviq staj na vseki direktor


------------------------
SELECT D.UCN, D.NAME, E.NAME, S.NUMBER, S.STARTDATE, D.BIRTHDATE, YEAR(S.STARTDATE - D.BIRTHDATE)
FROM DIRECTORS AS D, DIRECTS AS DR,
     EPISODES AS E, SEASONS AS S
WHERE D.UCN = DR.UCNDIRECTOR
AND DR.EPISODENAME = E.NAME
AND E.SEASONNUMBER = S.NUMBER#



SELECT D.UCN, D.NAME,
       (SELECT BIRTHDATE
        FROM DIRECTORS
        WHERE UCN = D.UCN) AS BIRTHDATE
FROM DIRECTORS AS D, DIRECTS AS DR,
     EPISODES AS E, SEASONS AS S
WHERE D.UCN = DR.UCNDIRECTOR
AND DR.EPISODENAME = E.NAME
AND E.SEASONNUMBER = S.NUMBER
GROUP BY D.UCN, D.NAME#

SELECT * FROM DIRECTORS#

SELECT E.NAME, E.SEASONNUMBER, S.STARTDATE
FROM EPISODES AS E, SEASONS AS S
WHERE E.SEASONNUMBER = S.NUMBER#



