SET SCHEMA FN71904#

-- скрипт за създаване на таблиците и ограниченията към тях

DROP TABLE SEASONS#
DROP TABLE EPISODES#
DROP TABLE TRAILERS#
DROP TABLE ACTORS#
DROP TABLE STARSIN#
DROP TABLE DIRECTORS#
DROP TABLE DIRECTS#
DROP TABLE USERS#
DROP TABLE EPISODEFORUMS#
DROP TABLE COMMENTS#


-- Сезони (номер, бройЕпизоди, датаНаИздаване, датаНаПриключване)
CREATE TABLE SEASONS(
    NUMBER INT NOT NULL CONSTRAINT PK_SEASONS PRIMARY KEY,
    EPISODESNO INT NOT NULL,
    STARTDATE  DATE,
    ENDDATE    DATE,
    CONSTRAINT CK_NUMBER CHECK (NUMBER >= 1 AND NUMBER <= 7),
    CONSTRAINT CK_EPISODESNO CHECK (EPISODESNO = 13 OR EPISODESNO = 16),
    CONSTRAINT CK_STARTDATE CHECK (STARTDATE <= ENDDATE),
    CONSTRAINT CK_ENDDATE CHECK (ENDDATE >= STARTDATE)
)#

-- Епизоди (име, номер, рейтинг, датаНаИздаване, времетраене, номерНаСезон)
CREATE TABLE EPISODES(
    NAME VARCHAR(50) NOT NULL CONSTRAINT PK_EPISODES PRIMARY KEY,
    NUMBER       INT NOT NULL,
    RATING       DECIMAL(3, 1),
    STARTDATE    DATE,
    LENGTH       TIME,
    SEASONNUMBER INT NOT NULL
    CONSTRAINT FK_EPISODES_SEASONS REFERENCES SEASONS (NUMBER),
    CONSTRAINT CK_NUMBER CHECK (NUMBER >= 1 AND NUMBER <= 16),
    CONSTRAINT CK_RATING CHECK (RATING >= 0 AND RATING <= 10)
)#

-- Трейлъри (датаНаИздаване, номерНаСезон, времетраене)
CREATE TABLE TRAILERS(
    STARTDATE    DATE NOT NULL,
    SEASONNUMBER INT  NOT NULL CONSTRAINT FK_TRAILERS_SEASONS REFERENCES SEASONS (NUMBER),
    LENGTH       TIME,
    PRIMARY KEY(STARTDATE, SEASONNUMBER),
    CONSTRAINT CK_SEASONNUMBER CHECK (SEASONNUMBER >= 1 AND SEASONNUMBER <= 7)
)#

--Актьори (игралноИме, реалноИме, датаНаРаждане)
CREATE TABLE ACTORS(
    SERIALNAME VARCHAR(50) NOT NULL CONSTRAINT PK_ACTORS PRIMARY KEY,
    REALNAME   VARCHAR(50) NOT NULL,
    BIRTHDATE  DATE        NOT NULL
)#

--Участва (имеНаЕпизод, игралноИмеНаАктьор)
CREATE TABLE STARSIN(
    EPISODENAME VARCHAR(50) NOT NULL CONSTRAINT FK_STARS_IN_EP REFERENCES EPISODES (NAME),
    ACTORNAME   VARCHAR(50) NOT NULL CONSTRAINT FK_STARS_IN_AC REFERENCES ACTORS (SERIALNAME),
    CONSTRAINT PK_STARS_IN PRIMARY KEY (EPISODENAME, ACTORNAME)
)#

--Директори (ЕГН, име, датаНаРаждане)
CREATE TABLE DIRECTORS(
    UCN CHAR(10)     NOT NULL CONSTRAINT PK_DIRECTORS PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    BIRTHDATE  DATE  NOT NULL
)#

--Ръководи (ЕГННаДиректор, имеНаЕпизод)
CREATE TABLE DIRECTS(
    UCNDIRECTOR CHAR(10)      NOT NULL CONSTRAINT FK_DIRECT_DIR REFERENCES DIRECTORS (UCN),
    EPISODENAME  VARCHAR(50) NOT NULL CONSTRAINT FK_DIRECT_EP REFERENCES EPISODES (NAME),
    CONSTRAINT PK_DIRECT PRIMARY KEY (UCNDIRECTOR, EPISODENAME)
)#

--Потребители (потребителскоИме, имейл, датаНаРаждане)
CREATE TABLE USERS(
    USERNAME VARCHAR(24) NOT NULL CONSTRAINT PK_USERNAME PRIMARY KEY,
    EMAIL    VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(16) NOT NULL
    CONSTRAINT CK_PASS     CHECK (LENGTH(PASSWORD) >= 8 AND LENGTH(PASSWORD) <= 16),
    CONSTRAINT CK_USERNAME CHECK (LENGTH(USERNAME) >= 6 AND LENGTH(USERNAME) <= 24)
)#

--EpisodeForums(име, бройКоментари, бройХаресвания, бройПосещения, датаНаСъздаване, имеНаЕпизод, потребителскоИме)
CREATE TABLE EPISODEFORUMS(
    NAME                VARCHAR(50) NOT NULL CONSTRAINT PK_EPISODEFORUMS_NAME PRIMARY KEY,
    CREATINGDATE        DATE        NOT NULL,
    TOTALCOMMENTSNUMBER INT         NOT NULL,
    LIKESNUMBER         INT         NOT NULL,
    VISITSNUMBER        INT         NOT NULL,
    USERNAME            VARCHAR(50) NOT NULL CONSTRAINT FK_EPISODEFORUMS_USERS REFERENCES USERS (USERNAME),
    EPISODENAME         VARCHAR(50) NOT NULL CONSTRAINT GK_EPISODEFORUMS_EPISODES REFERENCES EPISODES (NAME)
)#

--Коментари (номер, имеНаФорум, имеНаПотребител, текст, датаНаПубликуване)
CREATE TABLE COMMENTS(
    NUMBER            VARCHAR(64) NOT NULL,
    EPISODEFORUMNAME  VARCHAR(50) NOT NULL CONSTRAINT FK_COMMENTS_EPISODEFORUMS REFERENCES EPISODEFORUMS (NAME),
    USERNAME          VARCHAR(24) NOT NULL CONSTRAINT FK_COMMENTS_USERS REFERENCES USERS(USERNAME),
    TEXT              VARCHAR(500) NOT NULL,
    PUBLISHDATE       DATE NOT NULL,
    PRIMARY KEY(NUMBER, EPISODEFORUMNAME, USERNAME)
)#
